export const styles = {
    verticalButtonsStyle: (isEditing: boolean) => `flex flex-col items-center justify-center z-100 select-none transition-opacity duration-200 absolute -left-[2rem] top-1/2 -translate-y-1/2 h-fit min-w-[2rem] bg-gray-800 py-2 ${isEditing ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'}`,
    verticalButtonStyle: (isEditing: boolean) => `${isEditing ? 'pointer-events-auto' : 'pointer-events-none'} my-0.5 w-6 h-6 shadow-sm focus:outline-none cursor-pointer hover:transform hover:translate-x-1 m-1 transition-transform duration-150`,
    contextButtonsContainerStyle: 'absolute top-[-1.9rem] w-full h-[30px] select-none',
    contextButtonsWrapper: 'absolute bg-slate-800 focus:outline-none flex gap-[5px] p-1',
    contextButtonStyle: 'p-[2px] hover:transform hover:translate-y-1 px-[8px] text-[12px] cursor-pointer transition-transform duration-150',
    paragraphContainerStyle: (isEditing: boolean, isHighlighted: boolean, fontClass?: string) => `${isEditing ? 'border-t-2 border-slate-800 ' : ''}${isHighlighted ? 'bg-yellow-100 ' : ''}${isEditing || isHighlighted ? 'shadow-sm ' : ''}px-3 mb-1 text-slate-800 relative flex-1 ${fontClass || ''}`,
    paragraphStyle: (isEditing: boolean, characterCount: number, isQuote: boolean, textAlignment: string) => `${isEditing ? 'rounded':( characterCount === 0 ? 'bg-red-50' : '') + 'hover:border-y-2'} ${isQuote ? 'pl-[4rem] italic text-gray-600' : 'border-slate-300 border-dashed'} pr-2 pb-4 cursor-text min-h-[1.5rem] outline-none ${textAlignment}`,
    characterCountStyle: (isEditing: boolean) => `absolute right-0 bottom-0 text-gray-400 bg-slate-100 rounded px-2 translate-y-1/2 ${isEditing ? 'visible':'invisible group-hover:visible'}`,
    mainContainerStyle: 'relative flex flex-row items-stretch group is-paragraph',
    createNewParagraphAboveStyle: 'relative flex items-center justify-center box-border w-full cursor-pointer border-2 border-transparent hover:border-dashed hover:border-slate-400/30 hover:rounded-t-md hover:text-gray-400 transition-colors duration-200',
    isCursorAtFirstPositionStyle: 'absolute left-0 top-0 text-gray-400 -translate-y-1/2',
    isCursorAtLastPositionStyle: 'absolute left-0 bottom-0 text-gray-400 translate-y-1/2',
    isQuoteStyle: 'absolute pl-[3.5rem] left-0 top-0 select-none pointer-events-none',
    syncIndicatorStyle: 'absolute top-0 right-0',
};